model: 'tf_efficientnetv2_s_in21ft1k'
pretrained: True
embedding_length: 512
train_image_dir: ''
test_image_dir: ''
batch_size: 32
epochs: 15
force_cpu: False
stats_update_period: 1
saved_model_path: '../assideo_files/weights.pt'
save_type: 'weights' # weights or model
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]
embeddings_path: '../assideo_files/embeddings.pt'
dropout_proba: 0.1
criterion:
  name: 'arcface'
  scaling: 16
  margin: 0.05
optimizer:
  name: 'adamw'
  lr: 0.001
scheduler:
  name: 'exponential'
  gamma: 0.95
wandb:
  dir: ''
  project: 'image_retrieval'
